# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *default
  database: prod_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: production_db_name
